# Transform

## Import Packages

In [3]:
import os
import re
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
import requests

## Prepare

In [6]:
STORAGE_DIR = "../input"

In [8]:
OUTPUT_DIR = "../output"

In [10]:
DOC_DIR = "../docu"

In [12]:
FILE_DIR = os.path.join(OUTPUT_DIR, "cleaned_masterfile_df.csv")

## Load CSV-File

In [15]:
cleaned_masterfile_df = pd.read_csv(os.path.join(FILE_DIR), encoding="utf-8")

In [17]:
cleaned_masterfile_df = cleaned_masterfile_df.drop(cleaned_masterfile_df.columns[[0,1]],axis = 1)

In [19]:
cleaned_masterfile_df.head(3)

,id,title,preview,date,zeitschrift
0,teaser-httpswwwsueddeutschedepolitiksyrien-kur...,Einigung zwischen Kurden und Regierung,Die SDF einigen sich mit der syrischen Regieru...,2026-01-30,sz
1,teaser-httpswwwsueddeutschedepolitiksyrien-dam...,Damaskus und Kurden beschließen Waffenstillstand,Die kurdisch angeführten Syrischen Demokratisc...,2026-01-30,sz
2,teaser-httpswwwsueddeutschedemeinungiran-prote...,So verraten die Exil-Iraner ihr eigenes Volk,"Sie sind zerstritten, ja verfeindet. Dabei bra...",2026-01-30,sz

## Integration von OpenAI API

### Titel: Inhalt kategorisieren

In [21]:
title_df = cleaned_masterfile_df[["id", "title"]]

In [34]:
from openai import OpenAI
from pydantic import BaseModel

API_KEY = ""
client = OpenAI(api_key=API_KEY)


output = []

for i in range(len(title_df["title"])):
    int_text = str(title_df.at[i, "title"])
    print(f"Analysiere Titel {i+1}/{len(title_df)}: {int_text[:30]}...")
    response = client.chat.completions.create(
        model = 'gpt-5.2',
        messages = [
          {'role': 'system', 'content': (
                "Du bist ein wissenschaftlicher Assistent für Medienanalyse. "
                "Klassifiziere Medientitel in 'Vertrauen' oder 'Skepsis' basierend auf folgenden Kriterien:\n"
                "VERTRAUEN: Fokus auf Durchbruch, historische Chancen, Legitimität der Akteure und Zukunftslösungen.\n"
                "SKEPSIS: Fokus auf ungelöste Probleme, Misstrauen gegenüber Motiven, fragilen Charakter oder PR-Manöver.\n"
                "Antworte nur mit einem der beiden Begriffe.")},
          {'role': 'user', 'content': f"Titel zur Analyse: {int_text}"}
        ]
      )      
    chat_response = response.choices[0].message.content
    output.append(chat_response)

title_df["analyse_title"] = output

Analysiere Titel 1/683: Einigung zwischen Kurden und R...
Analysiere Titel 2/683: Damaskus und Kurden beschließe...
Analysiere Titel 3/683: So verraten die Exil-Iraner ih...
Analysiere Titel 4/683: Auch die Armee geht von 70 000...
Analysiere Titel 5/683: Israel will Gaza-Grenze nach Ä...
Analysiere Titel 6/683: Wo der Papagei in der Lobby di...
Analysiere Titel 7/683: Regime lässt Tausende Regierun...
Analysiere Titel 8/683: Syrien: Der kurdische Kampf um...
Analysiere Titel 9/683: EU setzt iranische Revolutions...
Analysiere Titel 10/683: Recherche nur unter Aufsicht...
Analysiere Titel 11/683: Trump mischt sich im Irak ein...
Analysiere Titel 12/683: Was die Revolutionsgarde anger...
Analysiere Titel 13/683: Sie zählen die Toten – und war...
Analysiere Titel 14/683: Die Toten zwischen uns...
Analysiere Titel 15/683: Was lässt Israel von Gaza übri...
Analysiere Titel 16/683: Alle Geiseln sind zurück, doch...
Analysiere Titel 17/683: Berichte: Irans Sicherheitskrä...
Analysiere Titel 18/683: Letzte Geisel im Gazastreifen ...
Analysiere Titel 19/683: Israelische Armee: Letzte tote...
Analysiere Titel 20/683: Tausende demonstrieren gegen M...
Analysiere Titel 21/683: Iran dementiert Stopp von Hinr...
Analysiere Titel 22/683: Liebe Menschheit, was macht ih...
Analysiere Titel 23/683: Was hier passiert, ist im Kern...
Analysiere Titel 24/683: Demonstration für die Menschen...
Analysiere Titel 25/683: Die Israelis wollen Aufklärung...
Analysiere Titel 26/683: Der Kämpfer, der für die syris...
Analysiere Titel 27/683: Verschleiern all die Tränen, d...
Analysiere Titel 28/683: Iran veröffentlicht offizielle...
Analysiere Titel 29/683: Wie Erdoğan die Kurden in Syri...
Analysiere Titel 30/683: Trump schickt einen Flugzeugtr...
Analysiere Titel 31/683: Wie die USA die Kurden im Stic...
Analysiere Titel 32/683: Ausschreitungen bei prokurdisc...
Analysiere Titel 33/683: Regierung und Kurdenmilizen ve...
Analysiere Titel 34/683: Israel reißt Gebäude auf UNRWA...
Analysiere Titel 35/683: Die Technokraten werden Gaza h...
Analysiere Titel 36/683: Kurdenmilizen ziehen von berüc...
Analysiere Titel 37/683: Iran: 40 000 Starlink-Terminal...
Analysiere Titel 38/683: Was ist ein Mullah?...
Analysiere Titel 39/683: Unabkömmlich in der instabilen...
Analysiere Titel 40/683: Weitere Proteste scheitern an ...
Analysiere Titel 41/683: Putin soll offenbar in Trumps ...
Analysiere Titel 42/683: Syrischer Übergangspräsident v...
Analysiere Titel 43/683: Dauerhafter Sitz in Trumps „Fr...
Analysiere Titel 44/683: „Sie haben mit Maschinengewehr...
Analysiere Titel 45/683: Offensive in Kurdengebiet...
Analysiere Titel 46/683: In Davos könnte Trump die Welt...
Analysiere Titel 47/683: Iran: „Nur noch eine Frage der...
Analysiere Titel 48/683: Die Strategie der Furcht geht ...
Analysiere Titel 49/683: Die Bundesregierung plant Absc...
Analysiere Titel 50/683: Trump wühlt die Weltwirtschaft...
Analysiere Titel 51/683: Menschen fliehen vor Kämpfen i...
Analysiere Titel 52/683: Schah Mohammad Reza Pahlavi...
Analysiere Titel 53/683: Der steinige Weg zum Frieden i...
Analysiere Titel 54/683: Warum Russland Iran kaum helfe...
Analysiere Titel 55/683: Nervöse Funkstille in Iran...
Analysiere Titel 56/683: Friedensplan für Gaza soll in ...
Analysiere Titel 57/683: Zweite Phase im Gaza-Friedensp...
Analysiere Titel 58/683: Alle warten, ob Trump Iran ang...
Analysiere Titel 59/683: Brics...
Analysiere Titel 60/683: Wie Trump Chinas Strategie dur...
Analysiere Titel 61/683: "Wie sollen wir gewinnen, ohne...
Analysiere Titel 62/683: Unicef meldet mehr als 100 tot...
Analysiere Titel 63/683: Pfauenthron...
Analysiere Titel 64/683: Wohl Tausende Tote bei Protest...
Analysiere Titel 65/683: Die Hisbollah verliert ihre wi...
Analysiere Titel 66/683: Warum Israel sich in Iran noch...
Analysiere Titel 67/683: Die Mullahs verordnen Stille...
Analysiere Titel 68/683: Wie Diktaturen dem Internet de...
Analysiere Titel 69/683: „Wir sehen die letzten Tage un...
Analysiere Titel 70/683: Merz: Sehen die letzten Tage u...
Analysiere Titel 71/683: Hören die USA den Deutschen üb...
Analysiere Titel 72/683: Was steht derzeit in Iran auf ...
Analysiere Titel 73/683: Von Israel unterstützte Miliz ...
Analysiere Titel 74/683: Außenminister: Lage ist unter ...
Analysiere Titel 75/683: USA greifen IS-Stellungen an...
Analysiere Titel 76/683: Das Mullah-Regime erlebt seine...
Analysiere Titel 77/683: Iran: Ist ein Systemwechsel mö...
Analysiere Titel 78/683: Europa verurteilt Gewalt gegen...
Analysiere Titel 79/683: Berichte: Kurdische Kämpfer ha...
Analysiere Titel 80/683: Krankenhäuser überfüllt – Trum...
Analysiere Titel 81/683: Israel und Hamas bereiten sich...
Analysiere Titel 82/683: Offenbar schwerste Kämpfe in A...
Analysiere Titel 83/683: Europa besorgt über Berichte a...
Analysiere Titel 84/683: Ex-Dax-Mitglied Covestro verlä...
Analysiere Titel 85/683: Kritiker des Mullah-Regimes fü...
Analysiere Titel 86/683: Ministerium appelliert an Kurd...
Analysiere Titel 87/683: Protestwelle in Iran – Geheimd...
Analysiere Titel 88/683: Verfassungsschutz warnt vor Ru...
Analysiere Titel 89/683: Er verkörpert den Traum von ei...
Analysiere Titel 90/683: Streit zwischen Regierung und ...
Analysiere Titel 91/683: „Wir können nicht mehr“...
Analysiere Titel 92/683: Präventivschlag angedroht...
Analysiere Titel 93/683: Die nächste Machtprobe für das...
Analysiere Titel 94/683: Benjamin beinhart...
Analysiere Titel 95/683: Britische und französische Luf...
Analysiere Titel 96/683: Separatisten kündigen Referend...
Analysiere Titel 97/683: Israel soll Gesetz zur Todesst...
Analysiere Titel 98/683: Israel fiebert mit iranischen ...
Analysiere Titel 99/683: Der gefährliche Aufstand der K...
Analysiere Titel 100/683: Trump droht Iran mit Eingreife...
Analysiere Titel 101/683: Massenproteste gegen Irans Reg...
Analysiere Titel 102/683: Spendengelder für Nahrung und ...
Analysiere Titel 103/683: Demonstrationen in Iran - erst...
Analysiere Titel 104/683: Israel wirft 37 Hilfsorganisat...
Analysiere Titel 105/683: Proteste weiten sich aus...
Analysiere Titel 106/683: Emirate ziehen Truppen ab...
Analysiere Titel 107/683: Jemens Regierung beendet Zusam...
Analysiere Titel 108/683: Revolution in der Geldbörse...
Analysiere Titel 109/683: Das sind die Reisetrends 2026...
Analysiere Titel 110/683: Ein Oligarch kauft sich frei...
Analysiere Titel 111/683: „Ich mache mir keine Sorgen da...
Analysiere Titel 112/683: Israel zückt das Lichtschwert...
Analysiere Titel 113/683: Hamas bestätigt Todesfälle...
Analysiere Titel 114/683: Was geschah mit Ron Arad?...
Analysiere Titel 115/683: Warum Israel als erster Staat ...
Analysiere Titel 116/683: 2025: Was wurde aus ICE-Deport...
Analysiere Titel 117/683: Ist das die „Migrationswende“?...
Analysiere Titel 118/683: Will Netanjahu Trump von einem...
Analysiere Titel 119/683: Was will Israel von Somaliland...
Analysiere Titel 120/683: Scharfe Kritik an Israel...
Analysiere Titel 121/683: Tote bei Anschlag auf Moschee...
Analysiere Titel 122/683: Keine deutschen Truppen nach G...
Analysiere Titel 123/683: Der Papst schärft sein Profil...
Analysiere Titel 124/683: Christen feiern erstmals wiede...
Analysiere Titel 125/683: Abschiebung nach Syrien...
Analysiere Titel 126/683: Israels Regierung plant Todess...
Analysiere Titel 127/683: Erstmals seit Kriegsbeginn: Ve...
Analysiere Titel 128/683: Israel will Armeesender schlie...
Analysiere Titel 129/683: Tech-Milliardär Ellison garant...
Analysiere Titel 130/683: Neue Siedlungen gebilligt...
Analysiere Titel 131/683: Kein Airbnb mehr, keine Master...
Analysiere Titel 132/683: US-Militär greift mehr als 70 ...
Analysiere Titel 133/683: Kritische Ernährungslage, aber...
Analysiere Titel 134/683: Wie Oman Deutschlands Stahlind...
Analysiere Titel 135/683: Reiche rüstet auf...
Analysiere Titel 136/683: Zwei Attentäter von nebenan...
Analysiere Titel 137/683: Anschlag in Sydney: „Es ging d...
Analysiere Titel 138/683: Mohammadis Familie berichtet v...
Analysiere Titel 139/683: Ihre 14. Festnahme...
Analysiere Titel 140/683: Israels Armee tötet Hamas-Komm...
Analysiere Titel 141/683: Islamischer Staat tötet drei U...
Analysiere Titel 142/683: Wintersturm „Byron“ fordert Me...
Analysiere Titel 143/683: Die Zerstörung geht weiter...
Analysiere Titel 144/683: Friedensnobelpreisträgerin fes...
Analysiere Titel 145/683: Jemen droht die Spaltung...
Analysiere Titel 146/683: „So was kenne ich aus dem Irak...
Analysiere Titel 147/683: Araber kaufen früheres Dax-Mit...
Analysiere Titel 148/683: Besuch bei den verdächtigten H...
Analysiere Titel 149/683: Linke ringt mit Antisemitismus...
Analysiere Titel 150/683: Netanjahu deutet Zugeständniss...
Analysiere Titel 151/683: Syriens starker Mann – clever ...
Analysiere Titel 152/683: Regierung verteidigt Kontakte ...
Analysiere Titel 153/683: Eine halbe Stunde Qual...
Analysiere Titel 154/683: Heute muss er unsichtbar sein...
Analysiere Titel 155/683: Frei nach 43 Jahren...
Analysiere Titel 156/683: Zwischen Vorurteil und Tatsach...
Analysiere Titel 157/683: Israel und Ägypten streiten üb...
Analysiere Titel 158/683: Sollte Deutschland sich von Is...
Analysiere Titel 159/683: Verhaftet, entlassen, flüchtig...
Analysiere Titel 160/683: Was ist das Damascus Dossier?...
Analysiere Titel 161/683: „Das Krankenhaus des Todes“: F...
Analysiere Titel 162/683: Das Archiv des Grauens...
Analysiere Titel 163/683: „Das Herz ist gebrochen“...
Analysiere Titel 164/683: Bilder einer Schreckensherrsch...
Analysiere Titel 165/683: Deutschland startet neues Rake...
Analysiere Titel 166/683: Grenzübergang Rafah soll bald ...
Analysiere Titel 167/683: Wiederaufbaukonferenz für Gaza...
Analysiere Titel 168/683: „Seid ihr bereit, Friedensstif...
Analysiere Titel 169/683: Waffenlager in Syrien zerstört...
Analysiere Titel 170/683: Gnadengesuch mit Berechnung...
Analysiere Titel 171/683: Ein Jahr nach Assad: Wie ist e...
Analysiere Titel 172/683: Netanjahu bittet um Begnadigun...
Analysiere Titel 173/683: Papst setzt Zeichen für Kirche...
Analysiere Titel 174/683: Wahrscheinlich mehr als 100 00...
Analysiere Titel 175/683: So wollen die Grünen wieder au...
Analysiere Titel 176/683: Militär tötet Mann im Gazastre...
Analysiere Titel 177/683: Israel greift in Syrien an...
Analysiere Titel 178/683: Wenn der Papst kommt, fließen ...
Analysiere Titel 179/683: Verbot von Palästina-Kongress ...
Analysiere Titel 180/683: Berlin verwarnt UN-Palästinens...
Analysiere Titel 181/683: Der Papst besucht als Erstes z...
Analysiere Titel 182/683: RSF-Miliz ruft einseitige Waff...
Analysiere Titel 183/683: Die Umsetzung des Friedensplan...
Analysiere Titel 184/683: "Ich bin fast ein Jahr in Syri...
Analysiere Titel 185/683: Israel tötet offenbar Hisbolla...
Analysiere Titel 186/683: Brüchige Waffenruhe in Gaza...
Analysiere Titel 187/683: Ein Held des 7. Oktober tritt ...
Analysiere Titel 188/683: Der mysteriöse Mullah...
Analysiere Titel 189/683: Die Widersprüche des Westens...
Analysiere Titel 190/683: Die fossile Energie spaltet de...
Analysiere Titel 191/683: Arabischer Staatskonzern übern...
Analysiere Titel 192/683: Mindestens 67 Kinder in Gaza g...
Analysiere Titel 193/683: Ist Greta Thunberg radikal?...
Analysiere Titel 194/683: Oberlandesgericht verhandelt K...
Analysiere Titel 195/683: Der Kronprinz hebt ab...
Analysiere Titel 196/683: Wenn der Außenminister innenpo...
Analysiere Titel 197/683: Gentleman...
Analysiere Titel 198/683: Trump zum Khashoggi-Mord: „Din...
Analysiere Titel 199/683: Störfeuer gegen Trumps Gaza-Pl...
Analysiere Titel 200/683: „Es gibt hier eine reale Macht...
Analysiere Titel 201/683: Trumps Frieden oder kein Fried...
Analysiere Titel 202/683: Rätselhafte Charterflüge nach ...
Analysiere Titel 203/683: Israel erhält wieder deutsche ...
Analysiere Titel 204/683: Meine schönsten Gaza-Selfies...
Analysiere Titel 205/683: Araber dürfen früheren Dax-Kon...
Analysiere Titel 206/683: Zwischenfälle in Gaza...
Analysiere Titel 207/683: EU-Kommission billigt Übernahm...
Analysiere Titel 208/683: Wie Netanjahu die Demokratie a...
Analysiere Titel 209/683: Pro-palästinensische Aktiviste...
Analysiere Titel 210/683: Ministerpräsident gewinnt Parl...
Analysiere Titel 211/683: Klagen gegen Waffenlieferungen...
Analysiere Titel 212/683: IAEA: Iran verletzt Regeln...
Analysiere Titel 213/683: Lange Haftstrafen gegen Syrer ...
Analysiere Titel 214/683: „Dann müssen wir Teheran evaku...
Analysiere Titel 215/683: Hamas übergibt Leiche...
Analysiere Titel 216/683: Was ist ein Konsulat?...
Analysiere Titel 217/683: „Es kommen jetzt mehr Kinder m...
Analysiere Titel 218/683: Iran will neues Konsulat in Bo...
Analysiere Titel 219/683: „Ohne Staatsbürgerschaft hätte...
Analysiere Titel 220/683: UN heben Sanktionen gegen al-S...
Analysiere Titel 221/683: UN-Sanktionen gegen Syriens Üb...
Analysiere Titel 222/683: Herbst des Verdrusses...
Analysiere Titel 223/683: Israel greift im Südlibanon an...
Analysiere Titel 224/683: Wadephul gibt nicht klein bei...
Analysiere Titel 225/683: Fünf Millionen Holocaust-Opfer...
Analysiere Titel 226/683: Eine „kommunikative Aufgabe“ f...
Analysiere Titel 227/683: Folter unter den Augen des Sta...
Analysiere Titel 228/683: USA werben für UN-Mandat der G...
Analysiere Titel 229/683: Lässt sich die Hamas entwaffne...
Analysiere Titel 230/683: Gerechtigkeit für einen Gaddaf...
Analysiere Titel 231/683: Syrien nach der Revolution: Sc...
Analysiere Titel 232/683: Die Union fremdelt mit ihrem e...
Analysiere Titel 233/683: Drei tote Geiseln identifizier...
Analysiere Titel 234/683: Welche Folgen Abschiebungen na...
Analysiere Titel 235/683: „Ein solches Ausmaß der Zerstö...
Analysiere Titel 236/683: UN: Ausmaß der Gräuel in al-Fa...
Analysiere Titel 237/683: Wie Friedrich Merz versucht, e...
Analysiere Titel 238/683: „Der Krieg ist nicht wirklich ...
Analysiere Titel 239/683: Der letzte Hippie des Kapitali...
Analysiere Titel 240/683: Gaza, ein Planspiel auf Kunstr...
Analysiere Titel 241/683: Erneute Angriffe auf Gaza: Ist...
Analysiere Titel 242/683: Trump sieht Gaza-Waffenruhe ni...
Analysiere Titel 243/683: Der erste Großmufti, der wenig...
Analysiere Titel 244/683: Wann spricht man von einem Kri...
Analysiere Titel 245/683: Der Autokrat, dennoch ein Staa...
Analysiere Titel 246/683: Neue Angriffe im Gazastreifen...
Analysiere Titel 247/683: Der Sultan lässt bitten...
Analysiere Titel 248/683: „Ich würde generell nicht empf...
Analysiere Titel 249/683: Westjordanland: Siedlergewalt ...
Analysiere Titel 250/683: Trump erhöht Druck auf Hamas...
Analysiere Titel 251/683: Im Schatten von Gaza...
Analysiere Titel 252/683: Der Mann, ohne den Netanjahu n...
Analysiere Titel 253/683: Israel muss Nahrung, Kleidung,...
Analysiere Titel 254/683: Vance spricht von einer „sehr ...
Analysiere Titel 255/683: „Wir sollten jetzt kämpfen“...
Analysiere Titel 256/683: Hilfe für den Gazastreifen...
Analysiere Titel 257/683: US-Vizepräsident auf Rettungsm...
Analysiere Titel 258/683: Meins, meins, meins...
Analysiere Titel 259/683: Israel öffnet Gaza-Grenzüberga...
Analysiere Titel 260/683: Wie Rafael Grossi eine Atomkat...
Analysiere Titel 261/683: Die Waffenruhe ist fragil...
Analysiere Titel 262/683: „Wir werden fragen: Wo wart ih...
Analysiere Titel 263/683: Machtvakuum Gaza: Zwischen Fri...
Analysiere Titel 264/683: Wie Trump versucht, das Tempo ...
Analysiere Titel 265/683: Eine Wahl unter Erdoğans Aufsi...
Analysiere Titel 266/683: „Die einzige Komponente, die B...
Analysiere Titel 267/683: Israel droht der Hamas...
Analysiere Titel 268/683: „Natürlich sind wir erleichter...
Analysiere Titel 269/683: Internationales Team soll offe...
Analysiere Titel 270/683: Heimkehr in den Widerstand...
Analysiere Titel 271/683: Weiß die Hamas wirklich nicht,...
Analysiere Titel 272/683: Netanjahu freut sich über Trum...
Analysiere Titel 273/683: Das sind die Männer, auf die e...
Analysiere Titel 274/683: Deutschland beginnt mit Hilfe ...
Analysiere Titel 275/683: Warum suchte sich Trump für di...
Analysiere Titel 276/683: „Es wird keinen dritten Weltkr...
Analysiere Titel 277/683: Geisel-Rückkehr: „Die Freude i...
Analysiere Titel 278/683: Trump beschwört Aufbruch für d...
Analysiere Titel 279/683: Die Hamas ist noch da...
Analysiere Titel 280/683: Trumps großer Tag...
Analysiere Titel 281/683: Freiheit, Erleichterung - und ...
Analysiere Titel 282/683: Die Lebenden und die Toten...
Analysiere Titel 283/683: Das sind die 20 Geiseln, die j...
Analysiere Titel 284/683: Israel erwartet die Rückkehr d...
Analysiere Titel 285/683: „Syrien ist am Limit“...
Analysiere Titel 286/683: Trumps Schwiegersohn als Schlü...
Analysiere Titel 287/683: Israelis feiern Trump als Supe...
Analysiere Titel 288/683: In Gaza schweigen die Waffen...
Analysiere Titel 289/683: Es ist nicht für alle vorbei...
Analysiere Titel 290/683: Endlich Friede in Nahost?...
Analysiere Titel 291/683: Für Netanjahu geht es mal wied...
Analysiere Titel 292/683: Gaza-Deal: Ist der Krieg vorbe...
Analysiere Titel 293/683: Als Deutsche über die Balkanro...
Analysiere Titel 294/683: „Du musst dem Negativen immer ...
Analysiere Titel 295/683: Der Beginn eines langen Wegs z...
Analysiere Titel 296/683: Trump verkündet Einigung bei G...
Analysiere Titel 297/683: Katar sieht Gaza-Verhandlungen...
Analysiere Titel 298/683: Ein Lebenszeichen und ein Wett...
Analysiere Titel 299/683: Waffenruhe in Aleppo...
Analysiere Titel 300/683: Gedenken an Israels Opfer, Pro...
Analysiere Titel 301/683: Eine Wahl voller Mängel, die t...
Analysiere Titel 302/683: Niemand bleibt unberührt...
Analysiere Titel 303/683: Hamas-Geiseln: 730 Tage Martyr...
Analysiere Titel 304/683: Israel und Hamas verhandeln üb...
Analysiere Titel 305/683: Stimmen für Palästina...
Analysiere Titel 306/683: Südafrika weist ranghöchsten i...
Analysiere Titel 307/683: Israel plant begrenzte Öffnung...
Analysiere Titel 308/683: Radikale Siedler, gefördert vo...
Analysiere Titel 309/683: Zwischen Wunschvorstellung und...
Analysiere Titel 310/683: Israels Armee meldet Fund letz...
Analysiere Titel 311/683: Kommission in Israel findet Mä...
Analysiere Titel 312/683: Israels Einfluss auf die USA s...
Analysiere Titel 313/683: Sie brüllen sich gegenseitig a...
Analysiere Titel 314/683: Plötzlich hat Netanjahu zum Ir...
Analysiere Titel 315/683: Die Zeugin, die Christina Bloc...
Analysiere Titel 316/683: Dobrindt unterzeichnet Cyber- ...
Analysiere Titel 317/683: Irans Präsident will Bürgern z...
Analysiere Titel 318/683: Israel und Syrien vereinbaren ...
Analysiere Titel 319/683: Israelischer Außenminister Gid...
Analysiere Titel 320/683: "Was droht, ist noch mehr Chao...
Analysiere Titel 321/683: Noch einmal zwischen den Front...
Analysiere Titel 322/683: Fast 6.000 Tote. Was nun?...
Analysiere Titel 323/683: Ein Vorposten gegen die Huthis...
Analysiere Titel 324/683: Iranische Justiz kündigt entsc...
Analysiere Titel 325/683: Trump droht, Netanjahu schweig...
Analysiere Titel 326/683: Kritik im UN-Sicherheitsrat na...
Analysiere Titel 327/683: Trump will Israel bei Angriffe...
Analysiere Titel 328/683: Herzog dementiert Trumps Aussa...
Analysiere Titel 329/683: Netanjahu schweigt, sein Umfel...
Analysiere Titel 330/683: Der Humor behält als Einziger ...
Analysiere Titel 331/683: Huthi-Miliz droht Israel mit m...
Analysiere Titel 332/683: 21 Staaten werfen Israel Völke...
Analysiere Titel 333/683: Irans Präsident wirft USA, Isr...
Analysiere Titel 334/683: Was will Israel von Somaliland...
Analysiere Titel 335/683: Mehrere Staaten weisen Anerken...
Analysiere Titel 336/683: Israel erkennt Somaliland als ...
Analysiere Titel 337/683: Israels Außenminister nennt Kr...
Analysiere Titel 338/683: Israel plant Milliardeninvesti...
Analysiere Titel 339/683: Was Bilder über das Jahr 2025 ...
Analysiere Titel 340/683: Israelischer Außenminister ruf...
Analysiere Titel 341/683: Israel beschließt den Bau von ...
Analysiere Titel 342/683: Iran vollstreckt offenbar Tode...

/var/folders/js/_xy2g5lx3x9bmk2ldqbkrm080000gq/T/ipykernel_6446/3959380417.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  title_df["analyse_title"] = output

### Vorschau: Inhalt kategorisieren

In [23]:
preview_df = cleaned_masterfile_df[["id", "preview"]]

In [32]:
from openai import OpenAI
from pydantic import BaseModel

API_KEY = ""
client = OpenAI(api_key=API_KEY)


output_preview = []

for i in range(len(preview_df["preview"])):
    int_text = str(preview_df.at[i, "preview"])
    print(f"Analysiere Titel {i+1}/{len(preview_df)}: {int_text[:30]}...")
    response = client.chat.completions.create(
        model = 'gpt-5.2',
        messages = [
          {'role': 'system', 'content': (
                "Du bist ein wissenschaftlicher Assistent für Medienanalyse. "
                "Klassifiziere Medientitel in 'Vertrauen' oder 'Skepsis' basierend auf folgenden Kriterien:\n"
                "VERTRAUEN: Fokus auf Durchbruch, historische Chancen, Legitimität der Akteure und Zukunftslösungen.\n"
                "SKEPSIS: Fokus auf ungelöste Probleme, Misstrauen gegenüber Motiven, fragilen Charakter oder PR-Manöver.\n"
                "Antworte nur mit einem der beiden Begriffe.")},
          {'role': 'user', 'content': f"Vorschau zur Analyse: {int_text}"}
        ]
      )      
    chat_response = response.choices[0].message.content
    output_preview.append(chat_response)

preview_df["analyse_preview"] = output_preview

Analysiere Titel 1/683: Die SDF einigen sich mit der s...
Analysiere Titel 2/683: Die kurdisch angeführten Syris...
Analysiere Titel 3/683: Sie sind zerstritten, ja verfe...
Analysiere Titel 4/683: Israels Militär geht israelisc...
Analysiere Titel 5/683: Israel will im Gazastreifen de...
Analysiere Titel 6/683: Das „Commodore“ war ein Hotel ...
Analysiere Titel 7/683: „Sie ‌verhaften jeden“, sagt e...
Analysiere Titel 8/683: Syriens Kurden wehren sich dag...
Analysiere Titel 9/683: Um sich an der Macht zu halten...
Analysiere Titel 10/683: Internationale Journalisten dü...
Analysiere Titel 11/683: Der ehemalige irakische Minist...
Analysiere Titel 12/683: In der Islamischen Republik ha...
Analysiere Titel 13/683: Vor einem Monat begannen die P...
Analysiere Titel 14/683: Vor mehr als 23 Jahren wurden ...
Analysiere Titel 15/683: Die „Gelbe Linie“, die fast di...
Analysiere Titel 16/683: Der Fund des toten Ran Gvili, ...
Analysiere Titel 17/683: Laut mehreren Berichten werden...
Analysiere Titel 18/683: Das israelische Militär hat di...
Analysiere Titel 19/683: Forensik-Experten haben die Le...
Analysiere Titel 20/683: Tausende Menschen sind am Sams...
Analysiere Titel 21/683: US-Präsident Trump hatte behau...
Analysiere Titel 22/683: Was in den ersten dreieinhalb ...
Analysiere Titel 23/683: Fans des israelischen Fußballk...
Analysiere Titel 24/683: Erneut haben sich in Berlin me...
Analysiere Titel 25/683: Welche Schuld trägt Israels Fü...
Analysiere Titel 26/683: Mazlum Abdi hat bei der PKK un...
Analysiere Titel 27/683: Ein grausames Regime, ein US-P...
Analysiere Titel 28/683: Aktivisten haben nach eigenen ...
Analysiere Titel 29/683: Syrische Regierungstruppen drä...
Analysiere Titel 30/683: Jeder kann sich nur wünschen, ...
Analysiere Titel 31/683: Als Verbündete der Amerikaner ...
Analysiere Titel 32/683: Statt der angemeldet 20 demons...
Analysiere Titel 33/683: Zwischen den Milizen und den R...
Analysiere Titel 34/683: Bundesentwicklungsministerin R...
Analysiere Titel 35/683: Der amerikanische Präsident wi...
Analysiere Titel 36/683: Die von Kurdenmilizen angeführ...
Analysiere Titel 37/683: Irans Sicherheitsbehörden habe...
Analysiere Titel 38/683: Er ist formal nichts anderes a...
Analysiere Titel 39/683: Syriens Präsident al-Scharaa w...
Analysiere Titel 40/683: Auf Irans Straßen ist es ruhig...
Analysiere Titel 41/683: Das vom US-Präsidenten erfunde...
Analysiere Titel 42/683: An der geplanten Reise al-Scha...
Analysiere Titel 43/683: Der Rat soll sich eigentlich m...
Analysiere Titel 44/683: Aus Iran dringt momentan kaum ...
Analysiere Titel 45/683: Nach monatelangen Bemühungen u...
Analysiere Titel 46/683: Diese Woche trifft sich die gl...
Analysiere Titel 47/683: Daniela Sepehri ist Deutsch-Ir...
Analysiere Titel 48/683: Das iranische Regime hat die P...
Analysiere Titel 49/683: Beim umstrittenen Besuch des s...
Analysiere Titel 50/683: Der US-Präsident verursacht mi...
Analysiere Titel 51/683: Tausende Menschen sind nach sy...
Analysiere Titel 52/683: 1979 stürzten die Iraner ihren...
Analysiere Titel 53/683: Die US-Regierung startet die z...
Analysiere Titel 54/683: Erst Syrien, dann Venezuela, j...
Analysiere Titel 55/683: Nach Warnungen aus Washington ...
Analysiere Titel 56/683: Unter anderem sind eine Überga...
Analysiere Titel 57/683: Die Umsetzung des Gaza-Frieden...
Analysiere Titel 58/683: Das Regime in Teheran scheint ...
Analysiere Titel 59/683: Diese Gruppe setzt ein Gegenge...
Analysiere Titel 60/683: Jahrelang investierte China do...
Analysiere Titel 61/683: Ob in den USA oder an der türk...
Analysiere Titel 62/683: Seit Beginn der Waffenruhe Anf...
Analysiere Titel 63/683: Ein persischer Schah eroberte ...
Analysiere Titel 64/683: Das Regime geht mit ungekannte...
Analysiere Titel 65/683: Fällt mit der Schwäche des ira...
Analysiere Titel 66/683: Ein Sturz des iranischen Regim...
Analysiere Titel 67/683: In Iran sollen Hunderte Protes...
Analysiere Titel 68/683: Nichts fürchten autoritäre Reg...
Analysiere Titel 69/683: Friedrich Merz äußert sich in ...
Analysiere Titel 70/683: Eine Staatsführung, die sich n...
Analysiere Titel 71/683: Themen von Venezuela bis Nahos...
Analysiere Titel 72/683: Bringen die Demonstranten das ...
Analysiere Titel 73/683: Eine von Israel unterstützte p...
Analysiere Titel 74/683: Das Mullah-Regime stellt die l...
Analysiere Titel 75/683: Das US-Militär hat am Samstag ...
Analysiere Titel 76/683: Die wenigen Berichte aus dem L...
Analysiere Titel 77/683: Seit Ende Dezember gibt es Pro...
Analysiere Titel 78/683: Die Proteste in Iran erreichen...
Analysiere Titel 79/683: In der Millionenstadt war es z...
Analysiere Titel 80/683: Seit rund zwei Wochen gehen Me...
Analysiere Titel 81/683: Die USA und Israel geben der i...
Analysiere Titel 82/683: In der syrischen Metropole rin...
Analysiere Titel 83/683: Die Proteste in Iran erreichen...
Analysiere Titel 84/683: Ein Staatskonzern aus Abu Dhab...
Analysiere Titel 85/683: Die Proteste in Iran haben nun...
Analysiere Titel 86/683: Das syrische Verteidigungsmini...
Analysiere Titel 87/683: Tränengas, brennende Fahrzeuge...
Analysiere Titel 88/683: Der Nachrichtendienst beobacht...
Analysiere Titel 89/683: Reza Pahlavi ist, wenn man so ...
Analysiere Titel 90/683: Nach Zusammenstößen zwischen k...
Analysiere Titel 91/683: Iran erlebt die vierte Protest...
Analysiere Titel 92/683: Inmitten von Protesten und mil...
Analysiere Titel 93/683: Erneute Proteste und nun auch ...
Analysiere Titel 94/683: Seit mehr als 30 Jahren prägt ...
Analysiere Titel 95/683: Der Angriff zielte auf eine un...
Analysiere Titel 96/683: Inmitten wachsender Spannungen...
Analysiere Titel 97/683: Israel muss nach den Worten vo...
Analysiere Titel 98/683: Anders als US-Präsident Donald...
Analysiere Titel 99/683: Die desolate Wirtschaftslage t...
Analysiere Titel 100/683: Die USA würden den Demonstrant...
Analysiere Titel 101/683: Seit Tagen gehen Iranerinnen u...
Analysiere Titel 102/683: Unter dem Deckmantel der Wohlt...
Analysiere Titel 103/683: Teheran versucht noch, die Dem...
Analysiere Titel 104/683: Ärzte ohne Grenzen und andere ...
Analysiere Titel 105/683: Die Proteste in der iranischen...
Analysiere Titel 106/683: Der Jemen steht nach mehr als ...
Analysiere Titel 107/683: Das Bündnis mit Saudi-Arabien ...
Analysiere Titel 108/683: Syrien bekommt neue Banknoten ...
Analysiere Titel 109/683: Kreuzfahrtreisende werden jüng...
Analysiere Titel 110/683: Der von der EU sanktionierte R...
Analysiere Titel 111/683: Bei einem Besuch in Florida wi...
Analysiere Titel 112/683: Die Laserkanone „Iron Beam“ so...
Analysiere Titel 113/683: Die islamistische Terrororgani...
Analysiere Titel 114/683: Der Geheimdienst Mossad soll i...
Analysiere Titel 115/683: Seit mehr als 30 Jahren kämpft...
Analysiere Titel 116/683: Was für ein Klima schaffen die...
Analysiere Titel 117/683: Im Wahlkampf hat die Bundesreg...
Analysiere Titel 118/683: Am Montag wird Israels Ministe...
Analysiere Titel 119/683: De facto ist Somaliland seit 1...
Analysiere Titel 120/683: Der UN-Sicherheitsrat kommt we...
Analysiere Titel 121/683: Erstmals seit dem Sturz von Ma...
Analysiere Titel 122/683: Deutschland wird sich nach Ang...
Analysiere Titel 123/683: Leo XIV. feiert in Rom seine e...
Analysiere Titel 124/683: Nach zwei Jahren mit kriegsbed...
Analysiere Titel 125/683: Erstmals seit Beginn des syris...
Analysiere Titel 126/683: Einem Gesetzentwurf zufolge so...
Analysiere Titel 127/683: Der Mann habe in Nordrhein-Wes...
Analysiere Titel 128/683: In einem umstrittenen Schritt ...
Analysiere Titel 129/683: Warner Brothers hat die Famili...
Analysiere Titel 130/683: Israel hat die Schaffung von 1...
Analysiere Titel 131/683: Gotscha Lortkipanidse hat vor ...
Analysiere Titel 132/683: US-Verteidigungsminister Hegse...
Analysiere Titel 133/683: Der Gazastreifen ist aus Sicht...
Analysiere Titel 134/683: Den hiesigen Hüttenwerken geht...
Analysiere Titel 135/683: Lange hat sich die Bundeswirts...
Analysiere Titel 136/683: Australiens Behörden versuchen...
Analysiere Titel 137/683: Für Josef Schuster, den Präsid...
Analysiere Titel 138/683: Drei Tage nach ihrer Verhaftun...
Analysiere Titel 139/683: Ende vergangenes Jahres war Na...
Analysiere Titel 140/683: Die Hamas sieht durch die gezi...
Analysiere Titel 141/683: US-Präsident Donald Trump künd...
Analysiere Titel 142/683: Heftige Regenfälle und starke ...
Analysiere Titel 143/683: Seit der Waffenruhe ist der Ga...
Analysiere Titel 144/683: In Iran haben Sicherheitskräft...
Analysiere Titel 145/683: Lange waren in dem arabischen ...
Analysiere Titel 146/683: Hudhaifa Al-Mashhadani leitet ...
Analysiere Titel 147/683: Das Geschäft ist vollzogen: De...
Analysiere Titel 148/683: Das Hilfswerk UNRWA für Paläst...
Analysiere Titel 149/683: In Berlin läuft es für die Par...
Analysiere Titel 150/683: Kommt wieder Bewegung in den F...
Analysiere Titel 151/683: Seit einem Jahr ist der einsti...
Analysiere Titel 152/683: Katar hat seine Kontakte zur i...
Analysiere Titel 153/683: Der Bundeskanzler will sich in...
Analysiere Titel 154/683: Am 8. Dezember 2024 floh Syrie...
Analysiere Titel 155/683: Syriens Regime hatte keinen Me...
Analysiere Titel 156/683: Die Ermittlungen gegen die frü...
Analysiere Titel 157/683: Die Regierung Netanjahu will d...
Analysiere Titel 158/683: „Wir müssen zum Existenzrecht ...
Analysiere Titel 159/683: Akten aus dem syrischen Geheim...
Analysiere Titel 160/683: Woher stammen die Daten? Was b...
Analysiere Titel 161/683: Verhaftet, gefoltert, getötet:...
Analysiere Titel 162/683: Im Militärkrankenhaus Harasta ...
Analysiere Titel 163/683: Mindestens 160 000 Menschen si...
Analysiere Titel 164/683: Verfolgung, Folter, Mord: Inte...
Analysiere Titel 165/683: Auf der Grenze zwischen Sachse...
Analysiere Titel 166/683: Im Gazastreifen soll der wicht...
Analysiere Titel 167/683: Außenminister Johann Wadephul ...
Analysiere Titel 168/683: Bei seiner ersten Auslandsreis...
Analysiere Titel 169/683: Das US-Militär hat gemeinsam m...
Analysiere Titel 170/683: Israels Premier Netanjahu bitt...
Analysiere Titel 171/683: Ist der Zeitpunkt für eine Rüc...
Analysiere Titel 172/683: Der wegen Korruption angeklagt...
Analysiere Titel 173/683: Mit einem Aufruf für die Einhe...
Analysiere Titel 174/683: Eine neue Studie belegt, dass ...
Analysiere Titel 175/683: Die Regierungszeit hat das Pro...
Analysiere Titel 176/683: Trotz der Waffenruhe im Gaza-K...
Analysiere Titel 177/683: Israelische Soldaten haben nac...
Analysiere Titel 178/683: Die Probleme in Libanon wird L...
Analysiere Titel 179/683: Der Abbruch eines sogenannten ...
Analysiere Titel 180/683: Jahrzehntelang hat Deutschland...
Analysiere Titel 181/683: Papst Leo bricht erstmals zu e...
Analysiere Titel 182/683: Nach der Intervention der USA ...
Analysiere Titel 183/683: Das Sterben im Gazastreifen ge...
Analysiere Titel 184/683: Von Berlin aus betrachtet ist ...
Analysiere Titel 185/683: Zwischen Weihnachtsmarkt und S...
Analysiere Titel 186/683: Nach einer erneuten Eskalation...
Analysiere Titel 187/683: Noam Tibon, 63, hat am 7. Okto...
Analysiere Titel 188/683: Über Ali Chamenei, Irans Obers...
Analysiere Titel 189/683: Wie zurechtfinden in der neuen...
Analysiere Titel 190/683: Eigentlich sollte die Klimakon...
Analysiere Titel 191/683: Covestro war früher die Kunsts...
Analysiere Titel 192/683: Seit Beginn der Waffenruhe am ...
Analysiere Titel 193/683: Als Teenagerin hat sie die grö...
Analysiere Titel 194/683: Fünf Männer sind angeklagt, we...
Analysiere Titel 195/683: Donald Trump sichert dem saudi...
Analysiere Titel 196/683: Für Bundesaußenminister Johann...
Analysiere Titel 197/683: Das Prädikat offenbart im heut...
Analysiere Titel 198/683: US-Präsident Donald Trump empf...
Analysiere Titel 199/683: Eine internationale Truppe sol...
Analysiere Titel 200/683: Mitten in Neukölln tobt der Na...
Analysiere Titel 201/683: Viele Details sind ungeklärt, ...
Analysiere Titel 202/683: Mehr als 300 Palästinenser sin...
Analysiere Titel 203/683: Im Sommer hatte die Bundesregi...
Analysiere Titel 204/683: Selten haben Soldaten so viel ...
Analysiere Titel 205/683: Der Kunststoffhersteller Coves...
Analysiere Titel 206/683: Trotz Waffenruhe ist palästine...
Analysiere Titel 207/683: Der Ölkonzern Adnoc aus Abu Dh...
Analysiere Titel 208/683: Israels Ministerpräsident vers...
Analysiere Titel 209/683: Drei pro-palästinensische Akti...
Analysiere Titel 210/683: Aus der Parlamentswahl im Irak...
Analysiere Titel 211/683: Palästinenser im Gazastreifen ...
Analysiere Titel 212/683: Iran kommt seinen Informations...
Analysiere Titel 213/683: Das Oberlandesgericht München ...
Analysiere Titel 214/683: Iran erlebt eine extreme Dürre...
Analysiere Titel 215/683: Die islamistische Palästinense...
Analysiere Titel 216/683: Vertretung eines Staates in ei...
Analysiere Titel 217/683: Der deutsche Arzt Jan Wynands ...
Analysiere Titel 218/683: Das Mullah-Regime plant eine V...
Analysiere Titel 219/683: Bundeskanzler Merz sieht für F...
Analysiere Titel 220/683: Der UN-Sicherheitsrat hat die ...
Analysiere Titel 221/683: Die USA werten das Votum als S...
Analysiere Titel 222/683: Eigentlich wollte Friedrich Me...
Analysiere Titel 223/683: Israels Armee hat nach eigenen...
Analysiere Titel 224/683: Der Außenminister verteidigt s...
Analysiere Titel 225/683: Die israelische Gedenkstätte Y...
Analysiere Titel 226/683: Kanzler Merz versucht, die Auf...
Analysiere Titel 227/683: Israel debattiert über den Rüc...
Analysiere Titel 228/683: Die Trump-Regierung verhandelt...
Analysiere Titel 229/683: Die palästinensische Terrorgru...
Analysiere Titel 230/683: Hannibal Gaddafi, umstrittener...
Analysiere Titel 231/683: Während Deutschland darüber di...
Analysiere Titel 232/683: Nach seinem Syrien-Besuch läss...
Analysiere Titel 233/683: Drei von der islamistischen Ha...
Analysiere Titel 234/683: Bundesinnenminister Dobrindt w...
Analysiere Titel 235/683: Nach einem Besuch in Damaskus ...
Analysiere Titel 236/683: Bei der Einnahme der Stadt sol...
Analysiere Titel 237/683: Mindestens einer der Schlüssel...
Analysiere Titel 238/683: Die Waffen sollten im Gazastre...
Analysiere Titel 239/683: Nachdem sein bester Freund Jer...
Analysiere Titel 240/683: In einem neu errichteten Koord...
Analysiere Titel 241/683: Die Situation zwischen Israel ...
Analysiere Titel 242/683: Israel wirft der Hamas den Bru...
Analysiere Titel 243/683: Der 90 Jahre alte Saleh al-Fau...
Analysiere Titel 244/683: Es gibt ihn, seit es Menschen ...
Analysiere Titel 245/683: Am Mittwoch reist Friedrich Me...
Analysiere Titel 246/683: Der israelische Ministerpräsid...
Analysiere Titel 247/683: Ob Gaza, Syrien oder die Ukrai...
Analysiere Titel 248/683: Drohnen bedrohen europäische S...
Analysiere Titel 249/683: Es war zwar nur eine Mehrheit ...
Analysiere Titel 250/683: Der US-Präsident und Außenmini...
Analysiere Titel 251/683: Ausgerechnet zum Besuch der US...
Analysiere Titel 252/683: Ron Dermer führte die Verhandl...
Analysiere Titel 253/683: Der Internationale Gerichtshof...
Analysiere Titel 254/683: Der US-Vizepräsident will den ...
Analysiere Titel 255/683: Bildungsministerin Karin Prien...
Analysiere Titel 256/683: Das Welternährungsprogramm (WF...
Analysiere Titel 257/683: J. D. Vance versucht in Nahost...
Analysiere Titel 258/683: Die Trumps vergolden die Präsi...
Analysiere Titel 259/683: Israel lässt wieder humanitäre...
Analysiere Titel 260/683: Der Chef der Internationalen A...
Analysiere Titel 261/683: Israel fliegt Luftangriffe auf...
Analysiere Titel 262/683: Wie ist das: Teenager sein im ...
Analysiere Titel 263/683: Nach Beginn des Waffenstillsta...
Analysiere Titel 264/683: Der US-Präsident droht der Ham...
Analysiere Titel 265/683: In Nordzypern, das nur die Tür...
Analysiere Titel 266/683: Der Libanon-Chef der Terrorgru...
Analysiere Titel 267/683: Israel fordert die islamistisc...
Analysiere Titel 268/683: Laith Arafeh ist Leiter der pa...
Analysiere Titel 269/683: Weil sich weiterhin mindestens...
Analysiere Titel 270/683: Im besetzten Westjordanland ha...
Analysiere Titel 271/683: Am Dienstag übergibt die Terro...
Analysiere Titel 272/683: In Jerusalem lobt der US-Präsi...
Analysiere Titel 273/683: Die Geiseln sind frei, die Gef...
Analysiere Titel 274/683: Um die Not im Gazastreifen zu ...
Analysiere Titel 275/683: Steve Witkoff kannten bis vor ...
Analysiere Titel 276/683: Trump erlebt in Israel und Ägy...
Analysiere Titel 277/683: Alle noch lebenden Geiseln sin...
Analysiere Titel 278/683: Israel feiert die Freilassung ...
Analysiere Titel 279/683: In Gaza und im Westjordanland ...
Analysiere Titel 280/683: Der Empfang in Israel und der ...
Analysiere Titel 281/683: Alle noch lebenden Geiseln sin...
Analysiere Titel 282/683: Am 738. Tag entlässt die Hamas...
Analysiere Titel 283/683: Die letzten Berichte der Geise...
Analysiere Titel 284/683: Alle 20 noch lebenden Entführt...
Analysiere Titel 285/683: Geht es nach der Bundesregieru...
Analysiere Titel 286/683: Dass US-Präsident Trump Israel...
Analysiere Titel 287/683: Hunderttausende jubeln in Tel ...
Analysiere Titel 288/683: Die israelische Armee beginnt ...
Analysiere Titel 289/683: Israel bereitet sich auf die R...
Analysiere Titel 290/683: So viele Anläufe dazu gab es s...
Analysiere Titel 291/683: Israels Kabinett stimmt der er...
Analysiere Titel 292/683: Trumps Deal für Gaza ist ein D...
Analysiere Titel 293/683: Marie-Janine Calic schildert e...
Analysiere Titel 294/683: Malakeh Jazmati flüchtete aus ...
Analysiere Titel 295/683: Auf Druck von Donald Trump ein...
Analysiere Titel 296/683: Dass sich die Hamas und Israel...
Analysiere Titel 297/683: Hamas, Israel und die USA verh...
Analysiere Titel 298/683: Seit dem 7. Oktober 2023 werde...
Analysiere Titel 299/683: Nach gewaltsamen Auseinanderse...
Analysiere Titel 300/683: Zum zweiten Jahrestag des Terr...
Analysiere Titel 301/683: Nach 53 Jahren Diktatur hat Sy...
Analysiere Titel 302/683: Seit zwei Jahren lassen Zigtau...
Analysiere Titel 303/683: Zwei Jahre nach dem Überfall d...
Analysiere Titel 304/683: Auf Grundlage des US-Friedensp...
Analysiere Titel 305/683: Nach zwei Jahren Krieg in Gaza...
Analysiere Titel 306/683: Israels stellvertretender Bots...
Analysiere Titel 307/683: Am Sonntag soll eine begrenzte...
Analysiere Titel 308/683: Organisierter und gewalttätige...
Analysiere Titel 309/683: Die letzte tote Geisel ist aus...
Analysiere Titel 310/683: Die israelische Armee hat die ...
Analysiere Titel 311/683: Eine israelische Kommission ha...
Analysiere Titel 312/683: Donald Trump übergeht mit sein...
Analysiere Titel 313/683: In Leipzigs linkem Connewitz d...
Analysiere Titel 314/683: Bis vor Kurzem rief Israels Pr...
Analysiere Titel 315/683: Die Geschäftspartnerin des mut...
Analysiere Titel 316/683: Der Bundesinnenminister hat in...
Analysiere Titel 317/683: Die Regierung sollte auf die S...
Analysiere Titel 318/683: Mit US-Unterstützung wollen Is...
Analysiere Titel 319/683: Nachdem Israel die Region Soma...
Analysiere Titel 320/683: Viele Menschen in Gaza kämpfen...
Analysiere Titel 321/683: Israel droht dem Libanon mit e...
Analysiere Titel 322/683: Vor 90 Jahren beginnt in Paläs...
Analysiere Titel 323/683: Israel hat das de facto unabhä...
Analysiere Titel 324/683: Seit Sonntag gibt es im Iran P...
Analysiere Titel 325/683: Das Treffen mit Donald Trump i...
Analysiere Titel 326/683: Israel hat Somaliland als unab...
Analysiere Titel 327/683: US-Präsident Trump hat militär...
Analysiere Titel 328/683: US-Donald Trump behauptet, für...
Analysiere Titel 329/683: Fünf Mal war Netanjahu bei Tru...
Analysiere Titel 330/683: Der Comedian Shahak Shapira ha...
Analysiere Titel 331/683: Die vom Iran finanzierten Huth...
Analysiere Titel 332/683: Die überwiegend muslimischen L...
Analysiere Titel 333/683: Irans Präsident Massud Pesesch...
Analysiere Titel 334/683: Arabische Staaten und die Türk...
Analysiere Titel 335/683: Die Afrikanische Union, die Tü...

/var/folders/js/_xy2g5lx3x9bmk2ldqbkrm080000gq/T/ipykernel_6446/803684993.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preview_df["analyse_preview"] = output_preview

## Create new Masterfile

In [55]:
merge_file = cleaned_masterfile_df.merge(preview_df[["id","analyse_preview"]], on="id")

In [63]:
final_merge_df = merge_file.merge(title_df[["id","analyse_title"]], on="id")

In [61]:
finale_merge_file.head(3)

,id,title,preview,date,zeitschrift,analyse_preview,analyse_title
0,teaser-httpswwwsueddeutschedepolitiksyrien-kur...,Einigung zwischen Kurden und Regierung,Die SDF einigen sich mit der syrischen Regieru...,2026-01-30,sz,Vertrauen,Vertrauen
1,teaser-httpswwwsueddeutschedepolitiksyrien-dam...,Damaskus und Kurden beschließen Waffenstillstand,Die kurdisch angeführten Syrischen Demokratisc...,2026-01-30,sz,Vertrauen,Vertrauen
2,teaser-httpswwwsueddeutschedemeinungiran-prote...,So verraten die Exil-Iraner ihr eigenes Volk,"Sie sind zerstritten, ja verfeindet. Dabei bra...",2026-01-30,sz,Skepsis,Skepsis

## Export new Masterfile to CSV

In [65]:
final_merge_df.to_csv(os.path.join(OUTPUT_DIR,"final_merge_df.csv"), sep=",")